### ISSUE TITLE
Problem php-tempalates

### ISSUE THREAD

**Issue by nofree** [overthemike/php-templates#1]
Hello, your code so very impressed... Clean and fast template engine, i like it!!
But it does not work with function while (on mysql), not repeat variable http://www.mediafire.com/?qmn7n81wi7evm01
I hope you can help me with this problem.
Thanks!

**Comment by overthemike** [comment]
Hey there. Sorry for the late response, but I honestly haven't touched this template thing for a while so I had to realign myself with it. In taking a quick look at your code, what you need to do is actually build the array inside of the while loop, and then AFTER the array is built, apply the template to it. I've made an example with the stuff you attached here -> https://gist.github.com/3152165 (I didn't test this so if it doesn't work, let me know and I'll take a closer look)

Something to keep in mind though...this template class, while hopefully working, isn't really maintained or anything. It was something I did as a contribution to a tutorial post I saw online. Feel free to use it of course, but consider taking a look at some really well maintained and highly recommended ones. A good example would be https://github.com/bobthecow/mustache.php

Good luck!

**Comment by nofree** [comment]
Display the correct category:
1. PC
   1. Power
   2. VGA
   3. RAM
   4. Audio
2. Laptop
   1. Monitor
   2. Pin
   3. Keyboard

After running:
1. PC
   1. Power
   2. VGA
   3. RAM
   4. Audio
   5. Monitor
   6. Pin
   7. Keyboard
2. Laptop
   1. Power
   2. VGA
   3. RAM
   4. Audio
   5. Monitor
   6. Pin
   7. Keyboard

Example: http://www.mediafire.com/?fln71mh5pwqjn7m

Why does a code fill all the space available to it?

Can you help me fix this code?

Thanks!
